name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository and Submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build
      run: ./scripts/cmake_release.sh

#    - name: Configure
#      run: ./configure
#    - name: Make
#      run: make
#    - name: Make Check
#      run: make check
#    - name: Make Distcheck
#      run: make distcheck
